# Generated by Django 5.0.14 on 2026-09-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('PRTG', 'PRTG Network Monitor'), ('NMS', 'Network Management System'), ('SYSLOG', 'Syslog Platform'), ('EMS', 'Element Management System'), ('SNMP_TRAP', 'SNMP Trap Receiver'), ('CUSTOM_API', 'Custom API')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Source-specific configuration')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(blank=True, help_text='Source-specific event identifier', max_length=255, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('event_status', models.CharField(db_index=True, max_length=20)),
                ('severity', models.CharField(default='CRITICAL', max_length=20)),
                ('event_time', models.DateTimeField(help_text='Timestamp from source (timezone-aware)')),
                ('received_time', models.DateTimeField(help_text='Timestamp when system received event')),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Source-specific metadata (e.g., prtg_device_id)')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Original payload for audit (sanitized)')),
                ('idempotency_key', models.CharField(db_index=True, help_text='SHA-256 hash for duplicate detection', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='devices.device')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventsource')),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['source', 'event_type', 'event_status'], name='events_netw_source__1612db_idx'), models.Index(fields=['device', 'event_type', 'event_status'], name='events_netw_device__ca8945_idx'), models.Index(fields=['-created_at'], name='events_netw_created_5e76e0_idx')],
            },
        ),
    ]
