# Generated by Django 5.0.14 on 2026-09-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('SNMP_SYSUPTIME', 'SNMP sysUpTime')], default='SNMP_SYSUPTIME', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('check_time', models.DateTimeField(blank=True, help_text='When the check was performed', null=True)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Structured verification result', null=True)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Evidence data (e.g., router_uptime_seconds, estimated_boot_time)', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='devices.device')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
