# Generated by Django 5.0.14 on 2026-09-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DOWN', 'Down'), ('RECOVERY_CHECK', 'Recovery Check'), ('RECOVERED', 'Recovered'), ('VERIFICATION_FAILED', 'Verification Failed'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required')], db_index=True, default='DOWN', max_length=30)),
                ('classification', models.CharField(blank=True, choices=[('DEVICE_REBOOT_RELATED', 'Device Reboot Related'), ('DEVICE_REBOOT_SUSPECTED', 'Device Reboot Suspected'), ('CONNECTIVITY_LOSS', 'Connectivity Loss'), ('UNABLE_TO_VERIFY', 'Unable to Verify')], max_length=50, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, null=True)),
                ('down_time', models.DateTimeField(help_text='When device first went down')),
                ('up_time', models.DateTimeField(blank=True, help_text='When device came back up', null=True)),
                ('last_seen', models.DateTimeField(help_text='Last event timestamp for this incident')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DOWN', 'Down'), ('DOWN_REPEAT', 'Down Repeat'), ('UP_RECEIVED', 'Up Received'), ('UP_WITHOUT_ACTIVE_INCIDENT', 'Up Without Active Incident'), ('SNMP_VERIFY_START', 'SNMP Verify Start'), ('SNMP_VERIFY_SUCCESS', 'SNMP Verify Success'), ('SNMP_VERIFY_FAILED', 'SNMP Verify Failed'), ('SNMP_VERIFY_RETRY', 'SNMP Verify Retry'), ('CLASSIFICATION_COMPLETED', 'Classification Completed'), ('RECOVERED', 'Recovered'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required')], max_length=50)),
                ('source', models.CharField(blank=True, default='', help_text='Which source generated this event', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional structured data for this timeline entry')),
                ('timestamp', models.DateTimeField(help_text='When this event occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incidents.incident')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('RELATED', 'Related'), ('SUPPORTING', 'Supporting'), ('RECOVERY', 'Recovery')], default='PRIMARY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_links', to='events.networkevent')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_events', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['primary_device', 'status'], name='incidents_i_primary_f47b07_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-down_time'], name='incidents_i_down_ti_afa357_idx'),
        ),
    ]
