# Generated by Django 5.0.14 on 2026-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_hardware_model_device_last_snmp_synced_at_and_more'),
        ('incidents', '0002_alter_eventtimeline_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='flap_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times link or device flapped during this incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('DEVICE', 'Device Reachability'), ('LINK', 'Link / Interface Status')], db_index=True, default='DEVICE', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='interface_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Interface or port name if incident_type is LINK', max_length=150),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_down_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent DOWN state transition', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_up_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent UP state transition', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='net_downtime_seconds',
            field=models.FloatField(default=0.0, help_text='Accumulated actual downtime across all flap cycles in seconds'),
        ),
        migrations.AddField(
            model_name='incident',
            name='prtg_sensor_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='PRTG sensor ID if from PRTG', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='soak_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp when continuous UP hold-down soak period completes', null=True),
        ),
        migrations.AlterField(
            model_name='eventtimeline',
            name='event_type',
            field=models.CharField(choices=[('DOWN', 'Down'), ('DOWN_REPEAT', 'Down Repeat'), ('UP_RECEIVED', 'Up Received'), ('UP_WITHOUT_ACTIVE_INCIDENT', 'Up Without Active Incident'), ('SNMP_VERIFY_START', 'SNMP Verify Start'), ('SNMP_VERIFY_SUCCESS', 'SNMP Verify Success'), ('SNMP_VERIFY_FAILED', 'SNMP Verify Failed'), ('SNMP_VERIFY_RETRY', 'SNMP Verify Retry'), ('CLASSIFICATION_COMPLETED', 'Classification Completed'), ('RECOVERED', 'Recovered'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required'), ('LINK_DOWN', 'Link Down'), ('LINK_UP', 'Link Up'), ('LINK_FLAP_DETECTED', 'Link Flap Detected'), ('SOAK_TIMER_START', 'Soak Timer Start'), ('SOAK_TIMER_RESET', 'Soak Timer Reset'), ('SOAK_TIMER_COMPLETED', 'Soak Timer Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='classification',
            field=models.CharField(blank=True, choices=[('DEVICE_REBOOT_RELATED', 'Device Reboot Related'), ('DEVICE_REBOOT_SUSPECTED', 'Device Reboot Suspected'), ('CONNECTIVITY_LOSS', 'Connectivity Loss'), ('UNABLE_TO_VERIFY', 'Unable to Verify'), ('PARENT_DEVICE_DOWN', 'Parent Device Down'), ('PHYSICAL_LINK_FAILURE', 'Physical Link Failure'), ('ADMIN_SHUTDOWN', 'Admin Shutdown'), ('LINK_FLAPPING', 'Link Flapping'), ('CONNECTIVITY_RECOVERED', 'Connectivity Recovered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='down_time',
            field=models.DateTimeField(help_text='When device or link first went down'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('DOWN', 'Down'), ('FLAPPING', 'Flapping'), ('STABILIZING', 'Stabilizing (Hold-down)'), ('RECOVERY_CHECK', 'Recovery Check'), ('RECOVERED', 'Recovered'), ('VERIFICATION_FAILED', 'Verification Failed'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required')], db_index=True, default='DOWN', max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='up_time',
            field=models.DateTimeField(blank=True, help_text='When device or link came back up permanently', null=True),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type', 'status'], name='incidents_i_inciden_b0a029_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['primary_device', 'interface_name', 'status'], name='incidents_i_primary_2621a9_idx'),
        ),
    ]
