# Generated by Django 5.0.14 on 2026-09-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_flap_count_incident_incident_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='classification',
            field=models.CharField(blank=True, choices=[('DEVICE_REBOOT_RELATED', 'Device Reboot Related'), ('DEVICE_REBOOT_SUSPECTED', 'Device Reboot Suspected'), ('CONNECTIVITY_LOSS', 'Connectivity Loss'), ('UNABLE_TO_VERIFY', 'Unable to Verify'), ('PARENT_DEVICE_DOWN', 'Parent Device Down'), ('PHYSICAL_LINK_FAILURE', 'Physical Link Failure'), ('ADMIN_SHUTDOWN', 'Admin Shutdown'), ('LINK_FLAPPING', 'Link Flapping'), ('TRANSIENT_GLITCH', 'Transient Glitch'), ('CONNECTIVITY_RECOVERED', 'Connectivity Recovered')], max_length=50, null=True),
        ),
    ]
