# Generated by Django 5.0.14 on 2026-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incident_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='link_description',
            field=models.CharField(blank=True, default='', help_text='Link description or circuit info extracted from PRTG sensor or ifAlias', max_length=300),
        ),
    ]
