# Generated by Django 5.0.14 on 2026-09-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_link_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='circuit_id',
            field=models.CharField(blank=True, default='', help_text='Circuit ID / NTID (e.g. TBB145020)', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='remote_device',
            field=models.CharField(blank=True, default='', help_text='Remote endpoint hostname or IP', max_length=150),
        ),
        migrations.AddField(
            model_name='incident',
            name='remote_interface',
            field=models.CharField(blank=True, default='', help_text='Remote endpoint interface name', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='site_name',
            field=models.CharField(blank=True, default='', help_text='Site / Station name', max_length=150),
        ),
        migrations.AddField(
            model_name='incident',
            name='ticket_id_tss',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Trouble Ticket ID from TSS/TTS (e.g. SD26094869)', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventtimeline',
            name='event_type',
            field=models.CharField(choices=[('DOWN', 'Down'), ('DOWN_REPEAT', 'Down Repeat'), ('UP_RECEIVED', 'Up Received'), ('UP_WITHOUT_ACTIVE_INCIDENT', 'Up Without Active Incident'), ('SNMP_VERIFY_START', 'SNMP Verify Start'), ('SNMP_VERIFY_SUCCESS', 'SNMP Verify Success'), ('SNMP_VERIFY_FAILED', 'SNMP Verify Failed'), ('SNMP_VERIFY_RETRY', 'SNMP Verify Retry'), ('CLASSIFICATION_COMPLETED', 'Classification Completed'), ('RECOVERED', 'Recovered'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required'), ('LINK_DOWN', 'Link Down'), ('LINK_UP', 'Link Up'), ('LINK_FLAP_DETECTED', 'Link Flap Detected'), ('SOAK_TIMER_START', 'Soak Timer Start'), ('SOAK_TIMER_RESET', 'Soak Timer Reset'), ('SOAK_TIMER_COMPLETED', 'Soak Timer Completed'), ('TICKET_LINKED', 'Ticket Linked')], max_length=50),
        ),
    ]
