# Generated by Django 5.0.14 on 2026-09-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incident_circuit_id_incident_remote_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='actual_cause',
            field=models.TextField(blank=True, default='', help_text='Actual root cause recorded by repair team in TTS'),
        ),
        migrations.AddField(
            model_name='incident',
            name='dest_gps',
            field=models.CharField(blank=True, default='', help_text='Destination location GPS coordinates (lat, lon)', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='repair_team',
            field=models.CharField(blank=True, default='', help_text='Responsible repair team from TTS', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution',
            field=models.TextField(blank=True, default='', help_text='Resolution action taken by repair team in TTS'),
        ),
        migrations.AddField(
            model_name='incident',
            name='response_department',
            field=models.CharField(blank=True, default='', help_text='Responsible department or area from TTS', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='source_gps',
            field=models.CharField(blank=True, default='', help_text='Source location GPS coordinates (lat, lon)', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='tts_status',
            field=models.CharField(blank=True, default='', help_text='Trouble Ticket status in ITSM/TTS (e.g. Work In Progress, Resolved, Closed)', max_length=50),
        ),
    ]
