# Generated by Django 5.0.14 on 2026-09-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedevicemapping',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='events.eventsource'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcedevicemapping',
            unique_together={('source', 'source_device_id')},
        ),
    ]
