# Generated by Django 5.0.14 on 2026-09-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Device metadata including optional snmp_community override'),
        ),
    ]
