# Generated by Django 5.0.14 on 2026-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hardware_model',
            field=models.CharField(blank=True, default='', help_text='Chassis model name from ENTITY-MIB', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='last_snmp_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful SNMP inventory sync', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_family',
            field=models.CharField(blank=True, default='', help_text='Operating system family (IOS-XR, IOS-XE, Classic IOS)', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='province',
            field=models.CharField(blank=True, default='', help_text='Full province name in Thai', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='province_code',
            field=models.CharField(blank=True, default='', help_text='2-letter province code (e.g. BK, CR, SP)', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='rca_strategy',
            field=models.CharField(blank=True, default='AUTO', help_text='RCA verification strategy: SSH_REBOOT_HISTORY or SNMP_WHY_RELOAD', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, default='', help_text='Chassis serial number from ENTITY-MIB', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='sys_name',
            field=models.CharField(blank=True, default='', help_text='Hostname queried from SNMP sysName', max_length=255),
        ),
    ]
