# Generated by Django 5.0.14 on 2026-09-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique configuration key, e.g. SNMP_COMMUNITY', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value')),
                ('category', models.CharField(choices=[('SNMP', 'SNMP Verification Settings'), ('THRESHOLD', 'Business Logic Thresholds'), ('INTEGRATION', 'Integration Settings'), ('GENERAL', 'General System Settings')], default='GENERAL', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what this setting controls')),
                ('is_secret', models.BooleanField(default=False, help_text='If True, masks value in UI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
