# Generated by Django 5.0.14 on 2026-09-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('SNMP', 'SNMP Verification Settings'), ('SSH', 'SSH Automation Settings'), ('THRESHOLD', 'Business Logic Thresholds'), ('INTEGRATION', 'Integration Settings'), ('GENERAL', 'General System Settings')], default='GENERAL', max_length=50),
        ),
    ]
